<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\InphicMouse.Core\InphicMouse.Core.csproj" />
    <ProjectReference Include="..\InphicMouse.Hid\InphicMouse.Hid.csproj" />
  </ItemGroup>
</Project>
